version: '3.8'

services:
  postgres:
    container_name: investhome_db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: investhome
      POSTGRES_USER: investhome_user
      POSTGRES_PASSWORD: investhome_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 