export enum DocumentType {
  PROPERTY_TITLE = 'PROPERTY_TITLE',
  FINANCIAL_STATEMENT = 'FINANCIAL_STATEMENT',
  TAX_RETURN = 'TAX_RETURN',
  INVESTMENT_AGREEMENT = 'INVESTMENT_AGREEMENT',
  PROPERTY_ASSESSMENT = 'PROPERTY_ASSESSMENT',
  LEGAL_VERIFICATION = 'LEGAL_VERIFICATION',
  OTHER = 'OTHER'
}

export enum DocumentStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED'
} 