name: Deploy Infrastructure

on:
  workflow_run:
    workflows: ["Backend CI/CD", "Frontend CI/CD"]
    types:
      - completed
    branches:
      - main
  push:
    paths:
      - 'infrastructure/**'
    branches:
          - main
  pull_request:
    paths:
      - 'infrastructure/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: ./infrastructure

    - name: Force new deployment of Backend
      if: ${{ github.event.workflow_run.name == 'Backend CI/CD' }}
      run: aws ecs update-service --cluster investhome-cluster --service backend --force-new-deployment

    - name: Force new deployment of Frontend
      if: ${{ github.event.workflow_run.name == 'Frontend CI/CD' }}
      run: aws ecs update-service --cluster investhome-cluster --service frontend --force-new-deployment

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./infrastructure 